version: 2

jobs:
  build:
    docker:
      - image: "circleci/node:8.15.0-browsers@sha256:db22685dec78d41dee90a9b2640eb7d5d7a47d8ef19530be9163d8c850b3c649"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
